@startuml
skinparam linetype ortho

storage HDD {
    folder vendorfiles as "vendor files"
}
rectangle inventory as "preserve.py inventory"
file inventory.csv as "manifest.csv"
collections accessions
collections locations
rectangle patsydb as "patsy-db"
rectangle patsydbdeposit as "patsy-db"
database PATSy
node libdpiprocessing {
    folder files
    file manifest.csv
    rectangle awsarchiver as "aws-archiver"
    rectangle DART as "dart-runner"
    collections keypaths as "key paths"
    package bag.tar {
        folder payload
    }
    rectangle apt_upload
}
file dartrunner as "dart-runner.json"
cloud AWS
cloud APTrust

inventory.csv --> manifest.csv
vendorfiles --> files

vendorfiles -> inventory
inventory --> inventory.csv
inventory.csv -> patsydb
patsydb -> accessions
accessions -> PATSy

files --> awsarchiver
manifest.csv --> awsarchiver
awsarchiver -> keypaths
keypaths -> AWS
manifest.csv <-- keypaths
manifest.csv -> patsydbdeposit
patsydbdeposit -> locations
PATSy <-- locations

files --> DART
DART --> bag.tar
bag.tar --> apt_upload
apt_upload --> APTrust
APTrust -> dartrunner
@enduml
