@startuml Digital Preservation Process
skinparam linetype ortho

storage HDD {
    folder vendorfiles as "vendor files"
}
rectangle inventory as "preserve.py inventory"
file inventory.csv as "manifest.csv"

rectangle patsydb as "patsy load"
rectangle patsydbdeposit as "patsy load"
node Kubernetes {
    database PATSy
    collections accessions
    collections locations
    rectangle patsyaptrust as "patsy sync"
}
node libdpiprocessing {
    folder files
    file manifest.csv
    rectangle awsarchiver as "aws-archiver"
    rectangle DART as "dart-runner"
    collections keypaths as "key paths"
    package bag.tar {
        folder payload
    }
    rectangle apt_upload
    file dartrunner_json as "dart-runner.json"
    file apt_upload_json as "apt_upload.json"
}
cloud AWS
cloud APTrust

inventory.csv --> manifest.csv
vendorfiles --> files

vendorfiles -> inventory
inventory --> inventory.csv
inventory.csv -> patsydb
patsydb -> accessions
accessions -> PATSy
APTrust --> patsyaptrust
patsyaptrust --> locations

files --> awsarchiver
manifest.csv --> awsarchiver
awsarchiver -> keypaths
keypaths -> AWS
manifest.csv <-- keypaths
manifest.csv -> patsydbdeposit
patsydbdeposit -> locations
PATSy <-- locations

files --> DART
DART ---> bag.tar
bag.tar --> apt_upload
apt_upload -> APTrust
APTrust ..> apt_upload_json
apt_upload --> apt_upload_json
DART --> dartrunner_json
@enduml
